In [3]:
import dataset
import torch
from torch.utils.data import Dataset, DataLoader

In [10]:
data = dataset.get_dataset()
data = data.get_data_folds()[0]

data.read_data()

In [14]:
# load data
train_data_generator = DataLoader(data.train, batch_size=1024, shuffle=True)
valid_data_generator = DataLoader(data.train, batch_size=1024, shuffle=True)
test_data_generator = DataLoader(data.train, batch_size=1024, shuffle=True)

In [18]:
data.train.num_docs(), data.train.num_queries()

(473092, 19943)

In [24]:
print(data.train.feature_matrix)
print(data.train.feature_matrix.shape)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.93693183 0.         0.         ... 0.         0.         0.33216909]
 [0.93693183 0.         0.         ... 0.         0.         0.01773038]
 ...
 [0.         0.         0.87005661 ... 0.         0.         0.43010739]
 [0.         0.         0.99959779 ... 0.         0.         0.7454519 ]
 [0.         0.         0.         ... 0.         0.62193749 0.58031631]]
(473092, 501)


In [25]:
print(data.train.label_vector)
print(data.train.label_vector.shape)

[0 1 0 ... 1 4 1]
(473092,)


In [37]:
data.train.num_queries()

19943

In [40]:
data.train.query_feat(1994).shape

(44, 501)

In [43]:
data.train.query_labels(1994).shape

(44,)

In [ ]:
# model

In [ ]:
# train